### ISSUE TITLE
[Question] experience with ProbabilisticOccupancyMap

### ISSUE THREAD

**Issue by facontidavide** [iris-ua/iris_lama#30]
Hi,

I noticed that the class FrequencyOccupancyMap seems to be preferred over the ProbabilisticOccupancyMap.

I have taken a look at the underlying algorithm and seems like the latter mimics the behavior of Octomap, somehow.

I wonder what your experience and recommendations are, when using one over the other.

**Comment by eupedrosa** [comment]
Hi @facontidavide.

In the literature, you will always find the `ProbabilisticOccupancyMap` as the "map" to use. But in practice, the `FrequencyOccupancyMap` provides better results for mapping. At least from my experience.

I usually use the `ProbabilistiOccupancyMap` for perception applications, where the occupancy map has to be more dynamic and quick to change. The `FrequencyOccupancyMap` is more conservative, it takes more effort (or observations) to go from occupiend to free.

And yes, the `ProbabilisticOccupancyMap` does mimic `Octomap`. But for integration, you can chose to use DDA like `Octomap` or the more simpler integer Bresenham algorithm, which is faster. The outcome is not very different due to the amount of data that we usually use in perception.

**Comment by facontidavide** [comment]
Thanks!
